<?php 
//This file was generated by calling php C:\PROGRA~1\APACHE~1\Apache2\htdocs\pos\generator.php statemachine 

//this script may only be included - so its better to die if called directly.
if (strpos($_SERVER["SCRIPT_NAME"],basename(__FILE__)) !== false) {
  header("location: index.php");
  exit;
}

require_once('statetoken.class.inc.php');
class statetoken extends generictable{
          private $observers;
         function __constructor()
         {
         $this->querytablename = 'statetoken';
         $this->fieldspec['statetoken_id']['metadata_id'] = '2921';
         $this->fieldspec['statetoken_id']['table_name'] = 'statetoken';
         $this->fieldspec['statetoken_id']['column_name'] = 'statetoken_id';
         $this->fieldspec['statetoken_id']['pretty_name'] = 'Table Key';
         $this->fieldspec['statetoken_id']['abstract_data_type'] = 'int';
         $this->fieldspec['statetoken_id']['db_data_type'] = 'int';
         $this->fieldspec['statetoken_id']['field_null'] = 'NO';
         $this->fieldspec['statetoken_id']['field_key'] = ' ';
         $this->fieldspec['statetoken_id']['extra_sql'] = ' ';
         $this->fieldspec['statetoken_id']['html_form_type'] = 'int';
         $this->fieldspec['statetoken_id']['html_form_options'] = ' ';
         $this->fieldspec['statetoken_id']['html_form_explanation'] = ' ';
         $this->fieldspec['statetoken_id']['help_text'] = ' ';
         $this->fieldspec['statetoken_id']['mandatory_p'] = 'Y';
         $this->fieldspec['statetoken_id']['sort_key'] = '0';
         $this->fieldspec['statetoken_id']['form_sort_key'] = '1';
         $this->fieldspec['statetoken_id']['form_number'] = '1';
         $this->fieldspec['statetoken_id']['default_value'] = ' ';
         $this->fieldspec['statetoken_id']['field_toupper'] = 'NO';
         $this->fieldspec['statetoken_id']['validationprocname'] = ' ';
         $this->fieldspec['statetoken_id']['c_size'] = '8';
         $this->fieldspec['statetoken_id']['prikey'] = 'Y';
         $this->fieldspec['statetoken_id']['noedit'] = 'N';
         $this->fieldspec['statetoken_id']['nodisplay'] = 'N';
         $this->fieldspec['statetoken_id']['c_unsigned'] = 'N';
         $this->fieldspec['statetoken_id']['c_zerofill'] = 'N';
         $this->fieldspec['statetoken_id']['c_auto_increment'] = 'N';
         $this->fieldspec['statetoken_id']['foreign_table'] = ' ';
         $this->fieldspec['statetoken_id']['foreign_key'] = ' ';
         $this->fieldspec['statetoken_id']['application'] = 'statemachine';
         $this->fieldspec['statetoken_id']['issearchable'] = '1';
         $this->fieldspec['statetoken_id']['preinserttrigger'] = ' ';
         $this->fieldspec['statetoken_id']['postinserttrigger'] = ' ';
         $this->fieldspec['statetoken_id']['preupdatetrigger'] = ' ';
         $this->fieldspec['statetoken_id']['postupdatetrigger'] = ' ';
         $this->fieldspec['statetoken_id']['predeletetrigger'] = ' ';
         $this->fieldspec['statetoken_id']['postdeletetrigger'] = ' ';
         $this->fieldspec['workflow_id']['metadata_id'] = '2922';
         $this->fieldspec['workflow_id']['table_name'] = 'statetoken';
         $this->fieldspec['workflow_id']['column_name'] = 'workflow_id';
         $this->fieldspec['workflow_id']['pretty_name'] = 'Workflow ID';
         $this->fieldspec['workflow_id']['abstract_data_type'] = 'int';
         $this->fieldspec['workflow_id']['db_data_type'] = 'int';
         $this->fieldspec['workflow_id']['field_null'] = 'NO';
         $this->fieldspec['workflow_id']['field_key'] = ' ';
         $this->fieldspec['workflow_id']['extra_sql'] = ' ';
         $this->fieldspec['workflow_id']['html_form_type'] = 'fddl';
         $this->fieldspec['workflow_id']['html_form_options'] = '<fk><field>workflow_id</field></fk>';
         $this->fieldspec['workflow_id']['html_form_explanation'] = ' ';
         $this->fieldspec['workflow_id']['help_text'] = ' ';
         $this->fieldspec['workflow_id']['mandatory_p'] = 'Y';
         $this->fieldspec['workflow_id']['sort_key'] = '0';
         $this->fieldspec['workflow_id']['form_sort_key'] = '2';
         $this->fieldspec['workflow_id']['form_number'] = '1';
         $this->fieldspec['workflow_id']['default_value'] = ' ';
         $this->fieldspec['workflow_id']['field_toupper'] = 'NO';
         $this->fieldspec['workflow_id']['validationprocname'] = ' ';
         $this->fieldspec['workflow_id']['c_size'] = '8';
         $this->fieldspec['workflow_id']['prikey'] = 'N';
         $this->fieldspec['workflow_id']['noedit'] = 'N';
         $this->fieldspec['workflow_id']['nodisplay'] = 'N';
         $this->fieldspec['workflow_id']['c_unsigned'] = 'N';
         $this->fieldspec['workflow_id']['c_zerofill'] = 'N';
         $this->fieldspec['workflow_id']['c_auto_increment'] = 'N';
         $this->fieldspec['workflow_id']['foreign_table'] = 'stateworkflow';
         $this->fieldspec['workflow_id']['foreign_key'] = 'workflow_id';
         $this->fieldspec['workflow_id']['application'] = 'statemachine';
         $this->fieldspec['workflow_id']['issearchable'] = '1';
         $this->fieldspec['workflow_id']['preinserttrigger'] = ' ';
         $this->fieldspec['workflow_id']['postinserttrigger'] = ' ';
         $this->fieldspec['workflow_id']['preupdatetrigger'] = ' ';
         $this->fieldspec['workflow_id']['postupdatetrigger'] = ' ';
         $this->fieldspec['workflow_id']['predeletetrigger'] = ' ';
         $this->fieldspec['workflow_id']['postdeletetrigger'] = ' ';
         $this->fieldspec['place_id']['metadata_id'] = '2923';
         $this->fieldspec['place_id']['table_name'] = 'statetoken';
         $this->fieldspec['place_id']['column_name'] = 'place_id';
         $this->fieldspec['place_id']['pretty_name'] = 'Place ID';
         $this->fieldspec['place_id']['abstract_data_type'] = 'int';
         $this->fieldspec['place_id']['db_data_type'] = 'int';
         $this->fieldspec['place_id']['field_null'] = 'NO';
         $this->fieldspec['place_id']['field_key'] = ' ';
         $this->fieldspec['place_id']['extra_sql'] = ' ';
         $this->fieldspec['place_id']['html_form_type'] = 'fddl';
         $this->fieldspec['place_id']['html_form_options'] = '<fk><field>place_id</field></fk>';
         $this->fieldspec['place_id']['html_form_explanation'] = ' ';
         $this->fieldspec['place_id']['help_text'] = ' ';
         $this->fieldspec['place_id']['mandatory_p'] = 'Y';
         $this->fieldspec['place_id']['sort_key'] = '0';
         $this->fieldspec['place_id']['form_sort_key'] = '3';
         $this->fieldspec['place_id']['form_number'] = '1';
         $this->fieldspec['place_id']['default_value'] = ' ';
         $this->fieldspec['place_id']['field_toupper'] = 'NO';
         $this->fieldspec['place_id']['validationprocname'] = ' ';
         $this->fieldspec['place_id']['c_size'] = '8';
         $this->fieldspec['place_id']['prikey'] = 'N';
         $this->fieldspec['place_id']['noedit'] = 'N';
         $this->fieldspec['place_id']['nodisplay'] = 'N';
         $this->fieldspec['place_id']['c_unsigned'] = 'N';
         $this->fieldspec['place_id']['c_zerofill'] = 'N';
         $this->fieldspec['place_id']['c_auto_increment'] = 'N';
         $this->fieldspec['place_id']['foreign_table'] = 'stateplace';
         $this->fieldspec['place_id']['foreign_key'] = 'place_id';
         $this->fieldspec['place_id']['application'] = 'statemachine';
         $this->fieldspec['place_id']['issearchable'] = '1';
         $this->fieldspec['place_id']['preinserttrigger'] = ' ';
         $this->fieldspec['place_id']['postinserttrigger'] = ' ';
         $this->fieldspec['place_id']['preupdatetrigger'] = ' ';
         $this->fieldspec['place_id']['postupdatetrigger'] = ' ';
         $this->fieldspec['place_id']['predeletetrigger'] = ' ';
         $this->fieldspec['place_id']['postdeletetrigger'] = ' ';
         $this->fieldspec['context']['metadata_id'] = '2924';
         $this->fieldspec['context']['table_name'] = 'statetoken';
         $this->fieldspec['context']['column_name'] = 'context';
         $this->fieldspec['context']['pretty_name'] = 'Context';
         $this->fieldspec['context']['abstract_data_type'] = 'varchar';
         $this->fieldspec['context']['db_data_type'] = 'int';
         $this->fieldspec['context']['field_null'] = 'NO';
         $this->fieldspec['context']['field_key'] = ' ';
         $this->fieldspec['context']['extra_sql'] = ' ';
         $this->fieldspec['context']['html_form_type'] = 'text';
         $this->fieldspec['context']['html_form_options'] = ' ';
         $this->fieldspec['context']['html_form_explanation'] = ' ';
         $this->fieldspec['context']['help_text'] = ' ';
         $this->fieldspec['context']['mandatory_p'] = 'Y';
         $this->fieldspec['context']['sort_key'] = '0';
         $this->fieldspec['context']['form_sort_key'] = '4';
         $this->fieldspec['context']['form_number'] = '1';
         $this->fieldspec['context']['default_value'] = ' ';
         $this->fieldspec['context']['field_toupper'] = 'YES';
         $this->fieldspec['context']['validationprocname'] = ' ';
         $this->fieldspec['context']['c_size'] = '32';
         $this->fieldspec['context']['prikey'] = 'N';
         $this->fieldspec['context']['noedit'] = 'N';
         $this->fieldspec['context']['nodisplay'] = 'N';
         $this->fieldspec['context']['c_unsigned'] = 'N';
         $this->fieldspec['context']['c_zerofill'] = 'N';
         $this->fieldspec['context']['c_auto_increment'] = 'N';
         $this->fieldspec['context']['foreign_table'] = ' ';
         $this->fieldspec['context']['foreign_key'] = ' ';
         $this->fieldspec['context']['application'] = 'statemachine';
         $this->fieldspec['context']['issearchable'] = '1';
         $this->fieldspec['context']['preinserttrigger'] = ' ';
         $this->fieldspec['context']['postinserttrigger'] = ' ';
         $this->fieldspec['context']['preupdatetrigger'] = ' ';
         $this->fieldspec['context']['postupdatetrigger'] = ' ';
         $this->fieldspec['context']['predeletetrigger'] = ' ';
         $this->fieldspec['context']['postdeletetrigger'] = ' ';
         $this->fieldlist = array('statetoken_id', 'workflow_id', 'place_id', 'context');
         $this->searchlist = array('statetoken_id', 'workflow_id', 'place_id', 'context');
	         return SUCCESS;
         }
         function statetoken()
         { //For older php which doesn't have constructor
              return $this->__constructor();
         }
         function Push()
         {
	         $_SESSION['statetoken'] = serialize($this);
	         return SUCCESS;
         }
         function Pop()
         {
                 //Can't do this in self - this is how to do it outside
	       //  $this = unserialize($_SESSION['statetoken']);
	         return SUCCESS;
         }
         function ObserverRegister( $observer)
         {
                 $this->observers[] = $observer;
	         return SUCCESS;
         }
         function ObserverDeRegister( $observer )
         {
                 $this->observers[] = array_diff( $this->observers, array( $observer) );
	         return SUCCESS;
         }
         function ObserverNotify()
         {
		if( isset( $this->observers ))
		{
                 	foreach ( $this->observers as $obs ) 
                 	{
                      		$obs->update( $this );
                 	}
	         	return SUCCESS;
		}
		else
			return FAILURE;
         }
         function Setcontext($value)
         {
                  $this->fieldspec['context']['VALUE'] = $value;
	          return SUCCESS;
         }
         function Getcontext()
         {
                    return $this->fieldspec['context']['VALUE'];
         }
         function Validatecontext()
         {
         }
} /* class statetoken */
