<?php 
//This file was generated by calling php C:\PROGRA~1\APACHE~1\Apache2\htdocs\pos\generator.php statemachine 

//this script may only be included - so its better to die if called directly.
if (strpos($_SERVER["SCRIPT_NAME"],basename(__FILE__)) !== false) {
  header("location: index.php");
  exit;
}

require_once('statearc.class.inc.php');
class statearc extends generictable{
          private $observers;
         function __constructor()
         {
         $this->querytablename = 'statearc';
         $this->fieldspec['workflow_id']['metadata_id'] = '2837';
         $this->fieldspec['workflow_id']['table_name'] = 'statearc';
         $this->fieldspec['workflow_id']['column_name'] = 'workflow_id';
         $this->fieldspec['workflow_id']['pretty_name'] = 'Workflow Process';
         $this->fieldspec['workflow_id']['abstract_data_type'] = 'smallint';
         $this->fieldspec['workflow_id']['db_data_type'] = 'smallint';
         $this->fieldspec['workflow_id']['field_null'] = 'YES';
         $this->fieldspec['workflow_id']['field_key'] = ' ';
         $this->fieldspec['workflow_id']['extra_sql'] = ' ';
         $this->fieldspec['workflow_id']['html_form_type'] = 'fddl';
         $this->fieldspec['workflow_id']['html_form_options'] = '<fk><field>workflow_name</field></fk>';
         $this->fieldspec['workflow_id']['html_form_explanation'] = ' ';
         $this->fieldspec['workflow_id']['help_text'] = ' ';
         $this->fieldspec['workflow_id']['mandatory_p'] = 'N';
         $this->fieldspec['workflow_id']['sort_key'] = '0';
         $this->fieldspec['workflow_id']['form_sort_key'] = '0';
         $this->fieldspec['workflow_id']['form_number'] = '1';
         $this->fieldspec['workflow_id']['default_value'] = ' ';
         $this->fieldspec['workflow_id']['field_toupper'] = 'NO';
         $this->fieldspec['workflow_id']['validationprocname'] = ' ';
         $this->fieldspec['workflow_id']['c_size'] = '5';
         $this->fieldspec['workflow_id']['prikey'] = 'Y';
         $this->fieldspec['workflow_id']['noedit'] = 'N';
         $this->fieldspec['workflow_id']['nodisplay'] = 'N';
         $this->fieldspec['workflow_id']['c_unsigned'] = 'Y';
         $this->fieldspec['workflow_id']['c_zerofill'] = 'N';
         $this->fieldspec['workflow_id']['c_auto_increment'] = 'N';
         $this->fieldspec['workflow_id']['foreign_table'] = 'stateworkflow';
         $this->fieldspec['workflow_id']['foreign_key'] = 'workflow_id';
         $this->fieldspec['workflow_id']['application'] = 'statemachine';
         $this->fieldspec['workflow_id']['issearchable'] = '1';
         $this->fieldspec['workflow_id']['preinserttrigger'] = ' ';
         $this->fieldspec['workflow_id']['postinserttrigger'] = ' ';
         $this->fieldspec['workflow_id']['preupdatetrigger'] = ' ';
         $this->fieldspec['workflow_id']['postupdatetrigger'] = ' ';
         $this->fieldspec['workflow_id']['predeletetrigger'] = '';
         $this->fieldspec['workflow_id']['postdeletetrigger'] = '';
         $this->fieldspec['transition_id']['metadata_id'] = '2838';
         $this->fieldspec['transition_id']['table_name'] = 'statearc';
         $this->fieldspec['transition_id']['column_name'] = 'transition_id';
         $this->fieldspec['transition_id']['pretty_name'] = 'Transition that this Arc connects to';
         $this->fieldspec['transition_id']['abstract_data_type'] = 'smallint';
         $this->fieldspec['transition_id']['db_data_type'] = 'smallint';
         $this->fieldspec['transition_id']['field_null'] = 'YES';
         $this->fieldspec['transition_id']['field_key'] = ' ';
         $this->fieldspec['transition_id']['extra_sql'] = ' ';
         $this->fieldspec['transition_id']['html_form_type'] = 'fddl';
         $this->fieldspec['transition_id']['html_form_options'] = '<fk><field>transition_name</field></fk>';
         $this->fieldspec['transition_id']['html_form_explanation'] = ' ';
         $this->fieldspec['transition_id']['help_text'] = ' ';
         $this->fieldspec['transition_id']['mandatory_p'] = 'N';
         $this->fieldspec['transition_id']['sort_key'] = '0';
         $this->fieldspec['transition_id']['form_sort_key'] = '0';
         $this->fieldspec['transition_id']['form_number'] = '1';
         $this->fieldspec['transition_id']['default_value'] = ' ';
         $this->fieldspec['transition_id']['field_toupper'] = 'NO';
         $this->fieldspec['transition_id']['validationprocname'] = ' ';
         $this->fieldspec['transition_id']['c_size'] = '5';
         $this->fieldspec['transition_id']['prikey'] = 'Y';
         $this->fieldspec['transition_id']['noedit'] = 'N';
         $this->fieldspec['transition_id']['nodisplay'] = 'N';
         $this->fieldspec['transition_id']['c_unsigned'] = 'Y';
         $this->fieldspec['transition_id']['c_zerofill'] = 'N';
         $this->fieldspec['transition_id']['c_auto_increment'] = 'N';
         $this->fieldspec['transition_id']['foreign_table'] = 'statetransition';
         $this->fieldspec['transition_id']['foreign_key'] = 'transition_id';
         $this->fieldspec['transition_id']['application'] = 'statemachine';
         $this->fieldspec['transition_id']['issearchable'] = '1';
         $this->fieldspec['transition_id']['preinserttrigger'] = ' ';
         $this->fieldspec['transition_id']['postinserttrigger'] = ' ';
         $this->fieldspec['transition_id']['preupdatetrigger'] = ' ';
         $this->fieldspec['transition_id']['postupdatetrigger'] = ' ';
         $this->fieldspec['transition_id']['predeletetrigger'] = '';
         $this->fieldspec['transition_id']['postdeletetrigger'] = '';
         $this->fieldspec['place_id']['metadata_id'] = '2839';
         $this->fieldspec['place_id']['table_name'] = 'statearc';
         $this->fieldspec['place_id']['column_name'] = 'place_id';
         $this->fieldspec['place_id']['pretty_name'] = 'Place that this Arc connects to';
         $this->fieldspec['place_id']['abstract_data_type'] = 'smallint';
         $this->fieldspec['place_id']['db_data_type'] = 'smallint';
         $this->fieldspec['place_id']['field_null'] = 'YES';
         $this->fieldspec['place_id']['field_key'] = ' ';
         $this->fieldspec['place_id']['extra_sql'] = ' ';
         $this->fieldspec['place_id']['html_form_type'] = 'fddl';
         $this->fieldspec['place_id']['html_form_options'] = '<fk><field>place_name</field></fk>';
         $this->fieldspec['place_id']['html_form_explanation'] = ' ';
         $this->fieldspec['place_id']['help_text'] = ' ';
         $this->fieldspec['place_id']['mandatory_p'] = 'N';
         $this->fieldspec['place_id']['sort_key'] = '0';
         $this->fieldspec['place_id']['form_sort_key'] = '0';
         $this->fieldspec['place_id']['form_number'] = '1';
         $this->fieldspec['place_id']['default_value'] = ' ';
         $this->fieldspec['place_id']['field_toupper'] = 'NO';
         $this->fieldspec['place_id']['validationprocname'] = ' ';
         $this->fieldspec['place_id']['c_size'] = '5';
         $this->fieldspec['place_id']['prikey'] = 'Y';
         $this->fieldspec['place_id']['noedit'] = 'N';
         $this->fieldspec['place_id']['nodisplay'] = 'N';
         $this->fieldspec['place_id']['c_unsigned'] = 'Y';
         $this->fieldspec['place_id']['c_zerofill'] = 'N';
         $this->fieldspec['place_id']['c_auto_increment'] = 'N';
         $this->fieldspec['place_id']['foreign_table'] = 'stateplace';
         $this->fieldspec['place_id']['foreign_key'] = 'place_id';
         $this->fieldspec['place_id']['application'] = 'statemachine';
         $this->fieldspec['place_id']['issearchable'] = '1';
         $this->fieldspec['place_id']['preinserttrigger'] = ' ';
         $this->fieldspec['place_id']['postinserttrigger'] = ' ';
         $this->fieldspec['place_id']['preupdatetrigger'] = ' ';
         $this->fieldspec['place_id']['postupdatetrigger'] = ' ';
         $this->fieldspec['place_id']['predeletetrigger'] = '';
         $this->fieldspec['place_id']['postdeletetrigger'] = '';
         $this->fieldspec['direction']['metadata_id'] = '2840';
         $this->fieldspec['direction']['table_name'] = 'statearc';
         $this->fieldspec['direction']['column_name'] = 'direction';
         $this->fieldspec['direction']['pretty_name'] = 'Direction of Arc (Into/Out of) Transition';
         $this->fieldspec['direction']['abstract_data_type'] = 'char';
         $this->fieldspec['direction']['db_data_type'] = 'char';
         $this->fieldspec['direction']['field_null'] = 'YES';
         $this->fieldspec['direction']['field_key'] = ' ';
         $this->fieldspec['direction']['extra_sql'] = ' ';
         $this->fieldspec['direction']['html_form_type'] = 'char';
         $this->fieldspec['direction']['html_form_options'] = ' ';
         $this->fieldspec['direction']['html_form_explanation'] = ' ';
         $this->fieldspec['direction']['help_text'] = ' ';
         $this->fieldspec['direction']['mandatory_p'] = 'N';
         $this->fieldspec['direction']['sort_key'] = '0';
         $this->fieldspec['direction']['form_sort_key'] = '0';
         $this->fieldspec['direction']['form_number'] = '1';
         $this->fieldspec['direction']['default_value'] = ' ';
         $this->fieldspec['direction']['field_toupper'] = 'NO';
         $this->fieldspec['direction']['validationprocname'] = ' ';
         $this->fieldspec['direction']['c_size'] = '3';
         $this->fieldspec['direction']['prikey'] = 'N';
         $this->fieldspec['direction']['noedit'] = 'N';
         $this->fieldspec['direction']['nodisplay'] = 'N';
         $this->fieldspec['direction']['c_unsigned'] = 'N';
         $this->fieldspec['direction']['c_zerofill'] = 'N';
         $this->fieldspec['direction']['c_auto_increment'] = 'N';
         $this->fieldspec['direction']['foreign_table'] = ' ';
         $this->fieldspec['direction']['foreign_key'] = ' ';
         $this->fieldspec['direction']['application'] = 'statemachine';
         $this->fieldspec['direction']['issearchable'] = '1';
         $this->fieldspec['direction']['preinserttrigger'] = ' ';
         $this->fieldspec['direction']['postinserttrigger'] = ' ';
         $this->fieldspec['direction']['preupdatetrigger'] = ' ';
         $this->fieldspec['direction']['postupdatetrigger'] = ' ';
         $this->fieldspec['direction']['predeletetrigger'] = '';
         $this->fieldspec['direction']['postdeletetrigger'] = '';
         $this->fieldspec['arc_type']['metadata_id'] = '2841';
         $this->fieldspec['arc_type']['table_name'] = 'statearc';
         $this->fieldspec['arc_type']['column_name'] = 'arc_type';
         $this->fieldspec['arc_type']['pretty_name'] = 'Arc Type (auto or manual)';
         $this->fieldspec['arc_type']['abstract_data_type'] = 'varchar';
         $this->fieldspec['arc_type']['db_data_type'] = 'varchar';
         $this->fieldspec['arc_type']['field_null'] = 'YES';
         $this->fieldspec['arc_type']['field_key'] = ' ';
         $this->fieldspec['arc_type']['extra_sql'] = ' ';
         $this->fieldspec['arc_type']['html_form_type'] = 'varchar';
         $this->fieldspec['arc_type']['html_form_options'] = ' ';
         $this->fieldspec['arc_type']['html_form_explanation'] = ' ';
         $this->fieldspec['arc_type']['help_text'] = ' ';
         $this->fieldspec['arc_type']['mandatory_p'] = 'N';
         $this->fieldspec['arc_type']['sort_key'] = '0';
         $this->fieldspec['arc_type']['form_sort_key'] = '0';
         $this->fieldspec['arc_type']['form_number'] = '1';
         $this->fieldspec['arc_type']['default_value'] = 'auto';
         $this->fieldspec['arc_type']['field_toupper'] = 'NO';
         $this->fieldspec['arc_type']['validationprocname'] = ' ';
         $this->fieldspec['arc_type']['c_size'] = '10';
         $this->fieldspec['arc_type']['prikey'] = 'N';
         $this->fieldspec['arc_type']['noedit'] = 'N';
         $this->fieldspec['arc_type']['nodisplay'] = 'N';
         $this->fieldspec['arc_type']['c_unsigned'] = 'N';
         $this->fieldspec['arc_type']['c_zerofill'] = 'N';
         $this->fieldspec['arc_type']['c_auto_increment'] = 'N';
         $this->fieldspec['arc_type']['foreign_table'] = ' ';
         $this->fieldspec['arc_type']['foreign_key'] = ' ';
         $this->fieldspec['arc_type']['application'] = 'statemachine';
         $this->fieldspec['arc_type']['issearchable'] = '1';
         $this->fieldspec['arc_type']['preinserttrigger'] = ' ';
         $this->fieldspec['arc_type']['postinserttrigger'] = ' ';
         $this->fieldspec['arc_type']['preupdatetrigger'] = ' ';
         $this->fieldspec['arc_type']['postupdatetrigger'] = ' ';
         $this->fieldspec['arc_type']['predeletetrigger'] = '';
         $this->fieldspec['arc_type']['postdeletetrigger'] = '';
         $this->fieldspec['pre_condition']['metadata_id'] = '2842';
         $this->fieldspec['pre_condition']['table_name'] = 'statearc';
         $this->fieldspec['pre_condition']['column_name'] = 'pre_condition';
         $this->fieldspec['pre_condition']['pretty_name'] = 'Precondition';
         $this->fieldspec['pre_condition']['abstract_data_type'] = 'text';
         $this->fieldspec['pre_condition']['db_data_type'] = 'text';
         $this->fieldspec['pre_condition']['field_null'] = 'NO';
         $this->fieldspec['pre_condition']['field_key'] = ' ';
         $this->fieldspec['pre_condition']['extra_sql'] = ' ';
         $this->fieldspec['pre_condition']['html_form_type'] = 'text';
         $this->fieldspec['pre_condition']['html_form_options'] = ' ';
         $this->fieldspec['pre_condition']['html_form_explanation'] = ' ';
         $this->fieldspec['pre_condition']['help_text'] = ' ';
         $this->fieldspec['pre_condition']['mandatory_p'] = 'N';
         $this->fieldspec['pre_condition']['sort_key'] = '0';
         $this->fieldspec['pre_condition']['form_sort_key'] = '0';
         $this->fieldspec['pre_condition']['form_number'] = '1';
         $this->fieldspec['pre_condition']['default_value'] = 'none';
         $this->fieldspec['pre_condition']['field_toupper'] = 'NO';
         $this->fieldspec['pre_condition']['validationprocname'] = ' ';
         $this->fieldspec['pre_condition']['c_size'] = '';
         $this->fieldspec['pre_condition']['prikey'] = 'N';
         $this->fieldspec['pre_condition']['noedit'] = 'N';
         $this->fieldspec['pre_condition']['nodisplay'] = 'N';
         $this->fieldspec['pre_condition']['c_unsigned'] = 'N';
         $this->fieldspec['pre_condition']['c_zerofill'] = 'N';
         $this->fieldspec['pre_condition']['c_auto_increment'] = 'N';
         $this->fieldspec['pre_condition']['foreign_table'] = ' ';
         $this->fieldspec['pre_condition']['foreign_key'] = ' ';
         $this->fieldspec['pre_condition']['application'] = 'statemachine';
         $this->fieldspec['pre_condition']['issearchable'] = '1';
         $this->fieldspec['pre_condition']['preinserttrigger'] = ' ';
         $this->fieldspec['pre_condition']['postinserttrigger'] = ' ';
         $this->fieldspec['pre_condition']['preupdatetrigger'] = ' ';
         $this->fieldspec['pre_condition']['postupdatetrigger'] = ' ';
         $this->fieldspec['pre_condition']['predeletetrigger'] = '';
         $this->fieldspec['pre_condition']['postdeletetrigger'] = '';
         $this->fieldspec['created_date']['metadata_id'] = '2843';
         $this->fieldspec['created_date']['table_name'] = 'statearc';
         $this->fieldspec['created_date']['column_name'] = 'created_date';
         $this->fieldspec['created_date']['pretty_name'] = ' ';
         $this->fieldspec['created_date']['abstract_data_type'] = 'datetime';
         $this->fieldspec['created_date']['db_data_type'] = 'datetime';
         $this->fieldspec['created_date']['field_null'] = 'YES';
         $this->fieldspec['created_date']['field_key'] = ' ';
         $this->fieldspec['created_date']['extra_sql'] = ' ';
         $this->fieldspec['created_date']['html_form_type'] = 'currentdate';
         $this->fieldspec['created_date']['html_form_options'] = ' ';
         $this->fieldspec['created_date']['html_form_explanation'] = ' ';
         $this->fieldspec['created_date']['help_text'] = ' ';
         $this->fieldspec['created_date']['mandatory_p'] = 'N';
         $this->fieldspec['created_date']['sort_key'] = '0';
         $this->fieldspec['created_date']['form_sort_key'] = '0';
         $this->fieldspec['created_date']['form_number'] = '1';
         $this->fieldspec['created_date']['default_value'] = ' ';
         $this->fieldspec['created_date']['field_toupper'] = 'NO';
         $this->fieldspec['created_date']['validationprocname'] = ' ';
         $this->fieldspec['created_date']['c_size'] = '';
         $this->fieldspec['created_date']['prikey'] = 'N';
         $this->fieldspec['created_date']['noedit'] = 'Y';
         $this->fieldspec['created_date']['nodisplay'] = 'Y';
         $this->fieldspec['created_date']['c_unsigned'] = 'N';
         $this->fieldspec['created_date']['c_zerofill'] = 'N';
         $this->fieldspec['created_date']['c_auto_increment'] = 'N';
         $this->fieldspec['created_date']['foreign_table'] = ' ';
         $this->fieldspec['created_date']['foreign_key'] = ' ';
         $this->fieldspec['created_date']['application'] = 'statemachine';
         $this->fieldspec['created_date']['issearchable'] = '1';
         $this->fieldspec['created_date']['preinserttrigger'] = ' ';
         $this->fieldspec['created_date']['postinserttrigger'] = ' ';
         $this->fieldspec['created_date']['preupdatetrigger'] = ' ';
         $this->fieldspec['created_date']['postupdatetrigger'] = ' ';
         $this->fieldspec['created_date']['predeletetrigger'] = '';
         $this->fieldspec['created_date']['postdeletetrigger'] = '';
         $this->fieldspec['created_user']['metadata_id'] = '2844';
         $this->fieldspec['created_user']['table_name'] = 'statearc';
         $this->fieldspec['created_user']['column_name'] = 'created_user';
         $this->fieldspec['created_user']['pretty_name'] = ' ';
         $this->fieldspec['created_user']['abstract_data_type'] = 'varchar';
         $this->fieldspec['created_user']['db_data_type'] = 'varchar';
         $this->fieldspec['created_user']['field_null'] = 'NO';
         $this->fieldspec['created_user']['field_key'] = ' ';
         $this->fieldspec['created_user']['extra_sql'] = ' ';
         $this->fieldspec['created_user']['html_form_type'] = 'currentuser';
         $this->fieldspec['created_user']['html_form_options'] = '<fk><field>username</field></fk>';
         $this->fieldspec['created_user']['html_form_explanation'] = ' ';
         $this->fieldspec['created_user']['help_text'] = ' ';
         $this->fieldspec['created_user']['mandatory_p'] = 'N';
         $this->fieldspec['created_user']['sort_key'] = '0';
         $this->fieldspec['created_user']['form_sort_key'] = '0';
         $this->fieldspec['created_user']['form_number'] = '1';
         $this->fieldspec['created_user']['default_value'] = ' ';
         $this->fieldspec['created_user']['field_toupper'] = 'NO';
         $this->fieldspec['created_user']['validationprocname'] = ' ';
         $this->fieldspec['created_user']['c_size'] = '16';
         $this->fieldspec['created_user']['prikey'] = 'N';
         $this->fieldspec['created_user']['noedit'] = 'N';
         $this->fieldspec['created_user']['nodisplay'] = 'N';
         $this->fieldspec['created_user']['c_unsigned'] = 'N';
         $this->fieldspec['created_user']['c_zerofill'] = 'N';
         $this->fieldspec['created_user']['c_auto_increment'] = 'N';
         $this->fieldspec['created_user']['foreign_table'] = 'users';
         $this->fieldspec['created_user']['foreign_key'] = 'username';
         $this->fieldspec['created_user']['application'] = 'statemachine';
         $this->fieldspec['created_user']['issearchable'] = '1';
         $this->fieldspec['created_user']['preinserttrigger'] = ' ';
         $this->fieldspec['created_user']['postinserttrigger'] = ' ';
         $this->fieldspec['created_user']['preupdatetrigger'] = ' ';
         $this->fieldspec['created_user']['postupdatetrigger'] = ' ';
         $this->fieldspec['created_user']['predeletetrigger'] = '';
         $this->fieldspec['created_user']['postdeletetrigger'] = '';
         $this->fieldspec['revised_date']['metadata_id'] = '2845';
         $this->fieldspec['revised_date']['table_name'] = 'statearc';
         $this->fieldspec['revised_date']['column_name'] = 'revised_date';
         $this->fieldspec['revised_date']['pretty_name'] = ' ';
         $this->fieldspec['revised_date']['abstract_data_type'] = 'datetime';
         $this->fieldspec['revised_date']['db_data_type'] = 'datetime';
         $this->fieldspec['revised_date']['field_null'] = 'NO';
         $this->fieldspec['revised_date']['field_key'] = ' ';
         $this->fieldspec['revised_date']['extra_sql'] = ' ';
         $this->fieldspec['revised_date']['html_form_type'] = 'currentdate';
         $this->fieldspec['revised_date']['html_form_options'] = ' ';
         $this->fieldspec['revised_date']['html_form_explanation'] = ' ';
         $this->fieldspec['revised_date']['help_text'] = ' ';
         $this->fieldspec['revised_date']['mandatory_p'] = 'N';
         $this->fieldspec['revised_date']['sort_key'] = '0';
         $this->fieldspec['revised_date']['form_sort_key'] = '0';
         $this->fieldspec['revised_date']['form_number'] = '1';
         $this->fieldspec['revised_date']['default_value'] = ' ';
         $this->fieldspec['revised_date']['field_toupper'] = 'NO';
         $this->fieldspec['revised_date']['validationprocname'] = ' ';
         $this->fieldspec['revised_date']['c_size'] = '';
         $this->fieldspec['revised_date']['prikey'] = 'N';
         $this->fieldspec['revised_date']['noedit'] = 'Y';
         $this->fieldspec['revised_date']['nodisplay'] = 'Y';
         $this->fieldspec['revised_date']['c_unsigned'] = 'N';
         $this->fieldspec['revised_date']['c_zerofill'] = 'N';
         $this->fieldspec['revised_date']['c_auto_increment'] = 'N';
         $this->fieldspec['revised_date']['foreign_table'] = ' ';
         $this->fieldspec['revised_date']['foreign_key'] = ' ';
         $this->fieldspec['revised_date']['application'] = 'statemachine';
         $this->fieldspec['revised_date']['issearchable'] = '1';
         $this->fieldspec['revised_date']['preinserttrigger'] = ' ';
         $this->fieldspec['revised_date']['postinserttrigger'] = ' ';
         $this->fieldspec['revised_date']['preupdatetrigger'] = ' ';
         $this->fieldspec['revised_date']['postupdatetrigger'] = ' ';
         $this->fieldspec['revised_date']['predeletetrigger'] = '';
         $this->fieldspec['revised_date']['postdeletetrigger'] = '';
         $this->fieldspec['revised_user']['metadata_id'] = '2846';
         $this->fieldspec['revised_user']['table_name'] = 'statearc';
         $this->fieldspec['revised_user']['column_name'] = 'revised_user';
         $this->fieldspec['revised_user']['pretty_name'] = ' ';
         $this->fieldspec['revised_user']['abstract_data_type'] = 'varchar';
         $this->fieldspec['revised_user']['db_data_type'] = 'varchar';
         $this->fieldspec['revised_user']['field_null'] = 'NO';
         $this->fieldspec['revised_user']['field_key'] = ' ';
         $this->fieldspec['revised_user']['extra_sql'] = ' ';
         $this->fieldspec['revised_user']['html_form_type'] = 'currentuser';
         $this->fieldspec['revised_user']['html_form_options'] = '<fk><field>username</field></fk>';
         $this->fieldspec['revised_user']['html_form_explanation'] = ' ';
         $this->fieldspec['revised_user']['help_text'] = ' ';
         $this->fieldspec['revised_user']['mandatory_p'] = 'N';
         $this->fieldspec['revised_user']['sort_key'] = '0';
         $this->fieldspec['revised_user']['form_sort_key'] = '0';
         $this->fieldspec['revised_user']['form_number'] = '1';
         $this->fieldspec['revised_user']['default_value'] = ' ';
         $this->fieldspec['revised_user']['field_toupper'] = 'NO';
         $this->fieldspec['revised_user']['validationprocname'] = ' ';
         $this->fieldspec['revised_user']['c_size'] = '16';
         $this->fieldspec['revised_user']['prikey'] = 'N';
         $this->fieldspec['revised_user']['noedit'] = 'N';
         $this->fieldspec['revised_user']['nodisplay'] = 'N';
         $this->fieldspec['revised_user']['c_unsigned'] = 'N';
         $this->fieldspec['revised_user']['c_zerofill'] = 'N';
         $this->fieldspec['revised_user']['c_auto_increment'] = 'N';
         $this->fieldspec['revised_user']['foreign_table'] = 'users';
         $this->fieldspec['revised_user']['foreign_key'] = 'username';
         $this->fieldspec['revised_user']['application'] = 'statemachine';
         $this->fieldspec['revised_user']['issearchable'] = '1';
         $this->fieldspec['revised_user']['preinserttrigger'] = ' ';
         $this->fieldspec['revised_user']['postinserttrigger'] = ' ';
         $this->fieldspec['revised_user']['preupdatetrigger'] = ' ';
         $this->fieldspec['revised_user']['postupdatetrigger'] = ' ';
         $this->fieldspec['revised_user']['predeletetrigger'] = '';
         $this->fieldspec['revised_user']['postdeletetrigger'] = '';
         $this->fieldlist = array('workflow_id', 'transition_id', 'place_id', 'direction', 'arc_type', 'pre_condition', 'created_date', 'created_user', 'revised_date', 'revised_user');
         $this->searchlist = array('workflow_id', 'transition_id', 'place_id', 'direction', 'arc_type', 'pre_condition', 'created_date', 'created_user', 'revised_date', 'revised_user');
	         return SUCCESS;
         }
         function statearc()
         { //For older php which doesn't have constructor
              return $this->__constructor();
         }
         function Push()
         {
	         $_SESSION['statearc'] = serialize($this);
	         return SUCCESS;
         }
         function Pop()
         {
                 //Can't do this in self - this is how to do it outside
	       //  $this = unserialize($_SESSION['statearc']);
	         return SUCCESS;
         }
         function ObserverRegister( $observer)
         {
                 $this->observers[] = $observer;
	         return SUCCESS;
         }
         function ObserverDeRegister( $observer )
         {
                 $this->observers[] = array_diff( $this->observers, array( $observer) );
	         return SUCCESS;
         }
         function ObserverNotify()
         {
                 foreach ( $this->observers as $obs ) 
                 {
                      $obs->update( $this );
                 }
	         return SUCCESS;
         }
         function Setrevised_user($value)
         {
                  $this->fieldspec['revised_user']['VALUE'] = $value;
	          return SUCCESS;
         }
         function Getrevised_user()
         {
                    return $this->fieldspec['revised_user']['VALUE'];
         }
         function Validaterevised_user()
         {
         }
} /* class statearc */
